import {useState} from 'react'
import {useDocumentOperation} from 'sanity'

export function DistributeArticle(props) {
  const {publish} = useDocumentOperation(props.id, props.type)
  const [isPublishing, setIsPublishing] = useState(false)

  if (props.type !== 'news') {
    return null
  }

  const handlePublish = async () => {
    setIsPublishing(true)
    
    try {
      // First, publish the article
      await publish.execute()
      
      // Get the published document
      const doc = props.draft || props.published
      const distribution = doc?.distribution
      
      if (!distribution) {
        console.log('No distribution settings, just publishing')
        setIsPublishing(false)
        return
      }

      const client = props.getClient({apiVersion: '2024-03-11'})
      const articleId = doc._id.replace('drafts.', '')
      
      const created = []
      const errors = []

      // 1. CREATE HERO SLIDE
      if (distribution.heroSlider) {
        try {
          const existingHero = await client.fetch(
            `*[_type == "heroSlide" && sourceArticle._ref == $articleId][0]`,
            {articleId}
          )
          
          if (!existingHero) {
            if (!doc.mainImage) {
              console.warn('⚠️ Cannot create hero slide: No image in article')
              errors.push('Hero Slide: No image in article')
            } else {
              const heroDoc = {
                _type: 'heroSlide',
                title: doc.title,
                subtitle: doc.excerpt?.substring(0, 150) || '',
                backgroundImage: {
                  _type: 'image',
                  asset: {
                    _type: 'reference',
                    _ref: doc.mainImage.asset._ref
                  }
                },
                tag: distribution.heroSliderTag || 'Featured',
                buttonText: 'Read Full Story',
                link: `/news/article.html?slug=${doc.slug.current}`,
                order: distribution.heroSliderPosition || 1,
                active: true,
                sourceArticle: {
                  _type: 'reference',
                  _ref: articleId,
                  _weak: true
                },
                autoGenerated: true
              }
              
              await client.create(heroDoc)
              created.push('Hero Slide')
              console.log('✓ Created hero slide')
            }
          } else {
            console.log('Hero slide already exists')
          }
        } catch (err) {
          console.error('✗ Hero slide error:', err.message)
          errors.push(`Hero Slide: ${err.message}`)
        }
      }

      // 2. CREATE QUICK HEADLINE
      if (distribution.quickHeadlines) {
        try {
          const existingHeadline = await client.fetch(
            `*[_type == "headline" && sourceArticle._ref == $articleId][0]`,
            {articleId}
          )
          
          if (!existingHeadline) {
            const headlineDoc = {
              _type: 'headline',
              title: doc.title,
              slug: {
                _type: 'slug',
                current: doc.slug.current
              },
              mainImage: doc.mainImage ? {
                _type: 'image',
                asset: {
                  _type: 'reference',
                  _ref: doc.mainImage.asset._ref
                }
              } : undefined,
              publishedAt: doc.publishedAt || new Date().toISOString(),
              category: doc.category,
              link: `/news/article.html?slug=${doc.slug.current}`,
              featured: true,
              order: distribution.quickHeadlinesPosition || 1,
              sourceArticle: {
                _type: 'reference',
                _ref: articleId,
                _weak: true
              },
              autoGenerated: true
            }
            
            await client.create(headlineDoc)
            created.push('Quick Headline')
            console.log('✓ Created quick headline')
          } else {
            console.log('Headline already exists')
          }
        } catch (err) {
          console.error('✗ Headline error:', err.message)
          errors.push(`Quick Headline: ${err.message}`)
        }
      }

      // 3. UPDATE CANADIAN CORNER
      if (distribution.canadianCorner) {
        try {
          let cornerDoc = await client.fetch(`*[_type == "canadianCorner"][0]`)
          
          if (!cornerDoc) {
            cornerDoc = await client.create({
              _type: 'canadianCorner',
              title: 'Canadian Corner'
            })
            console.log('✓ Created Canadian Corner document')
          }

          const position = distribution.canadianCornerPosition || 'sidebar-1'
          
          if (position === 'featured') {
            const articleData = {
              title: doc.title,
              slug: {
                _type: 'slug',
                current: doc.slug.current
              },
              mainImage: doc.mainImage ? {
                _type: 'image',
                asset: {
                  _type: 'reference',
                  _ref: doc.mainImage.asset._ref
                }
              } : undefined,
              excerpt: doc.excerpt?.substring(0, 200) || '',
              link: `/news/article.html?slug=${doc.slug.current}`,
              tag: 'Canadian Corner'
            }
            
            await client
              .patch(cornerDoc._id)
              .set({featuredArticle: articleData})
              .commit()
            created.push('Canadian Corner (Featured)')
            console.log('✓ Set as Canadian Corner featured article')
          } else {
            const sidebarIndex = parseInt(position.split('-')[1]) - 1
            let currentSidebar = cornerDoc.sidebarArticles || []
            
            while (currentSidebar.length < 3) {
              currentSidebar.push(null)
            }
            
            currentSidebar[sidebarIndex] = {
              title: doc.title,
              link: `/news/article.html?slug=${doc.slug.current}`,
              publishedAt: getTimeAgoString(doc.publishedAt),
              excerpt: doc.excerpt?.substring(0, 100) || ''
            }
            
            await client
              .patch(cornerDoc._id)
              .set({sidebarArticles: currentSidebar.filter(Boolean)})
              .commit()
            created.push(`Canadian Corner (Sidebar ${sidebarIndex + 1})`)
            console.log(`✓ Added to Canadian Corner sidebar position ${sidebarIndex + 1}`)
          }
        } catch (err) {
          console.error('✗ Canadian Corner error:', err.message)
          errors.push(`Canadian Corner: ${err.message}`)
        }
      }

      let message = ''
      if (created.length > 0) {
        message = `✓ Published & Distributed to: ${created.join(', ')}`
        if (errors.length > 0) {
          message += `\n⚠️ Errors: ${errors.join(', ')}`
        }
      } else if (errors.length > 0) {
        message = `✗ Failed to distribute: ${errors.join(', ')}`
      } else {
        message = '✓ Article published (no distribution selected)'
      }
      
      if (props.onComplete) {
        props.onComplete({message})
      }

    } catch (err) {
      console.error('Distribution error:', err)
      if (props.onComplete) {
        props.onComplete({
          message: `✗ Error: ${err.message}`
        })
      }
    } finally {
      setIsPublishing(false)
    }
  }
  
  function getTimeAgoString(dateString) {
    if (!dateString) return 'Just now'
    const date = new Date(dateString)
    const now = new Date()
    const seconds = Math.floor((now - date) / 1000)
    
    const intervals = [
      {label: 'year', seconds: 31536000},
      {label: 'month', seconds: 2592000},
      {label: 'day', seconds: 86400},
      {label: 'hour', seconds: 3600},
      {label: 'minute', seconds: 60}
    ]
    
    for (const interval of intervals) {
      const count = Math.floor(seconds / interval.seconds)
      if (count >= 1) {
        return `${count} ${interval.label}${count > 1 ? 's' : ''} ago`
      }
    }
    return 'Just now'
  }

  return {
    label: isPublishing ? 'Publishing & Distributing...' : '📢 Publish & Distribute',
    onHandle: handlePublish,
    disabled: publish.disabled || isPublishing,
    tone: 'positive'
  }
}

export default DistributeArticle