export default {
  name: 'headline',
  title: 'Quick Headlines',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Headline Title',
      type: 'string',
      validation: Rule => Rule.required()
    },
    {
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96
      }
    },
    {
      name: 'mainImage',
      title: 'Headline Image',
      type: 'image',
      options: {
        hotspot: true
      }
    },
    {
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      initialValue: () => new Date().toISOString()
    },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          {title: 'Serie A', value: 'serie-a'},
          {title: 'EPL', value: 'epl'},
          {title: 'La Liga', value: 'la-liga'},
          {title: 'UCL', value: 'ucl'},
          {title: 'World Cup', value: 'world-cup'},
          {title: 'Concacaf/MLS', value: 'concacaf-mls'},
          {title: 'South America', value: 'south-america'},
          {title: 'World Football', value: 'world-football'},
          {title: 'Transfers', value: 'transfers'},
          {title: 'Canadian Corner', value: 'canadian-corner'},
          {title: 'Breaking', value: 'breaking'}
        ]
      }
    },
    {
      name: 'link',
      title: 'Link URL',
      type: 'string',
      description: 'URL to full article'
    },
    {
      name: 'featured',
      title: 'Featured on Homepage',
      type: 'boolean',
      description: 'Show in the 6-headline row?',
      initialValue: true
    },
    {
      name: 'order',
      title: 'Display Order',
      type: 'number',
      description: 'Lower numbers show first (1-6 appear on homepage)',
      validation: Rule => Rule.min(1).max(20)
    },
    {
      name: 'sourceArticle',
      title: 'Source Article',
      type: 'reference',
      to: [{type: 'news'}],
      description: 'Link back to original news article',
      readOnly: true,
      hidden: true
    },
    {
      name: 'autoGenerated',
      title: 'Auto-Generated',
      type: 'boolean',
      description: 'Created automatically from news article',
      initialValue: false,
      readOnly: true,
      hidden: true
    }
  ],
  orderings: [
    {
      title: 'Display Order',
      name: 'orderAsc',
      by: [{field: 'order', direction: 'asc'}]
    },
    {
      title: 'Published Date',
      name: 'publishedAtDesc',
      by: [{field: 'publishedAt', direction: 'desc'}]
    }
  ],
  preview: {
    select: {
      title: 'title',
      media: 'mainImage',
      category: 'category',
      order: 'order',
      autoGenerated: 'autoGenerated'
    },
    prepare({title, media, category, order, autoGenerated}) {
      return {
        title: title || 'Untitled Headline',
        subtitle: `#${order || '?'} • ${category ? category.toUpperCase() : 'No category'}${autoGenerated ? ' 🤖 Auto' : ''}`,
        media
      }
    }
  }
}