export default {
  name: 'heroSlide',
  title: 'Hero Slides',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Slide Headline',
      type: 'string',
      description: 'Big text on the slide (e.g., "Messi Scores Hat-Trick")',
      validation: Rule => Rule.required()
    },
    {
      name: 'subtitle',
      title: 'Subtitle',
      type: 'text',
      rows: 2,
      description: 'Smaller text under the headline'
    },
    {
      name: 'backgroundImage',
      title: 'Background Image',
      type: 'image',
      description: '1920x1080px recommended',
      options: {
        hotspot: true
      },
      validation: Rule => Rule.required()
    },
    {
      name: 'tag',
      title: 'Tag (Breaking/Featured/etc)',
      type: 'string',
      options: {
        list: [
          {title: 'Breaking', value: 'Breaking'},
          {title: 'Exclusive', value: 'Exclusive'},
          {title: 'Featured', value: 'Featured'},
          {title: 'New Episode', value: 'New Episode'},
          {title: 'Canadian Corner', value: 'Canadian Corner'},
          {title: 'Hot Take', value: 'Hot Take'},
          {title: 'Analysis', value: 'Analysis'},
          {title: 'New Drop', value: 'New Drop'}
        ]
      },
      initialValue: 'Featured'
    },
    {
      name: 'buttonText',
      title: 'Button Text',
      type: 'string',
      initialValue: 'Read Full Story'
    },
    {
      name: 'link',
      title: 'Link URL',
      type: 'string',
      description: 'Where the button goes'
    },
    {
      name: 'order',
      title: 'Slide Order',
      type: 'number',
      description: '1 = first slide, 2 = second, etc.',
      validation: Rule => Rule.min(1).max(10)
    },
    {
      name: 'active',
      title: 'Active',
      type: 'boolean',
      description: 'Show this slide?',
      initialValue: true
    },
    {
      name: 'sourceArticle',
      title: 'Source Article',
      type: 'reference',
      to: [{type: 'news'}],
      description: 'Link back to original news article',
      readOnly: true,
      hidden: true
    },
    {
      name: 'autoGenerated',
      title: 'Auto-Generated',
      type: 'boolean',
      description: 'Created automatically from news article',
      initialValue: false,
      readOnly: true,
      hidden: true
    }
  ],
  orderings: [
    {
      title: 'Slide Order',
      name: 'orderAsc',
      by: [{field: 'order', direction: 'asc'}]
    }
  ],
  preview: {
    select: {
      title: 'title',
      tag: 'tag',
      order: 'order',
      autoGenerated: 'autoGenerated'
    },
    prepare({title, tag, order, autoGenerated}) {
      return {
        title: title || 'Untitled Slide',
        subtitle: `#${order || '?'} • ${tag || 'No tag'}${autoGenerated ? ' 🤖 Auto' : ''}`
      }
    }
  }
}